application: onelinr
version: 4
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: .*
  script: onelinr.py
